server:
  port: 3000

spring:
  application:
    name: reaction-commerce-api
  
  data:
    mongodb:
      uri: ${MONGO_URL:mongodb://localhost:27017/reaction}
      auto-index-creation: true
  
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
    path: /graphql
    websocket:
      path: /graphql
  
  security:
    user:
      name: admin
      password: ${ADMIN_PASSWORD:admin123}
  
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when_authorized

logging:
  level:
    com.reactioncommerce: DEBUG
    org.springframework.graphql: DEBUG
    org.springframework.data.mongodb: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Application specific configuration
reaction:
  cors:
    allowed-origins: ${ALLOWED_ORIGINS:http://localhost:3000,http://localhost:4000}
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
    allow-credentials: true
  
  security:
    jwt:
      secret: ${JWT_SECRET:mySecretKey}
      expiration: 86400000 # 24 hours in milliseconds
  
  shop:
    default-currency: USD
    default-language: en
  
  email:
    smtp:
      host: ${SMTP_HOST:localhost}
      port: ${SMTP_PORT:587}
      username: ${SMTP_USERNAME:}
      password: ${SMTP_PASSWORD:}
      auth: ${SMTP_AUTH:true}
      starttls: ${SMTP_STARTTLS:true}

---
spring:
  config:
    activate:
      on-profile: development

logging:
  level:
    root: INFO
    com.reactioncommerce: DEBUG

---
spring:
  config:
    activate:
      on-profile: production

logging:
  level:
    root: WARN
    com.reactioncommerce: INFO
